services:
  - type: web
    name: property-tracker-webapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webapp.py"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
